### PR TITLE
build: move sources

### PR DESCRIPTION
**Pull request by feckert**
Since the application is also integrated in the LuCI. But the project has a different folder structure it is not so easy to port the changes with patches. To make this work better and to make it easier to apply the changes in both projects, the folder structure was adapted to the LuCI project. Also the LuCI makefile was added but will not get used.

### CODE REVIEW

**Comment by feckert** [comment]
@lisaac what do you think?

**Comment by lisaac** [comment]
yes, but we need to change github workflows and README as well, I'll update it later.

**Comment by feckert** [comment]
Ok so lets merge this in this repository and then you could update the README and the workflow.

**Comment by feckert** [comment]
Thanks for the merge

**Pull request merged**
